In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
#Array creation
a = np.array(10)
type(a)

numpy.ndarray

In [7]:
#Zero dimentional array
z = np.array(10)
z.ndim

0

In [8]:
#1st dimaentional array
b = np.array([10,11,12,13])
b.ndim

1

In [9]:
#2 dimentional array
c = np.array([[10,12,13,14,15]])
c.ndim

2

In [10]:
#three dimanetional array
th = np.array ([[[10,12,13,14,15,16]]])
th.ndim

3

In [11]:
#change the data type of array elements.
a = np.array([10,15,52,54])

In [12]:
a.dtype

dtype('int32')

In [15]:
a = np.array([10,15,52,54], dtype = 'float')
print(a.dtype)
print('hello')
a

float64
hello


array([10., 15., 52., 54.])

# Other ways of creation an array

* arange
* linspace
* zeros
* ones
* random 

In [16]:
#Arrange 
a = np.arange(1,21,2,)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
#linspace


In [18]:
b = np.linspace(1,5,15,retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [19]:
z# zeros


array(10)

In [20]:
z = np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [21]:
#ones


In [22]:
o = np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
#random

In [24]:
r = np.random.rand(5,5)
r

array([[0.18162858, 0.5067065 , 0.62191705, 0.59917891, 0.69050779],
       [0.13271083, 0.4931091 , 0.11324725, 0.12362731, 0.44436043],
       [0.86870772, 0.3865666 , 0.33486768, 0.19591672, 0.27701529],
       [0.24911731, 0.23848968, 0.13335463, 0.00679075, 0.08116861],
       [0.26383296, 0.70037667, 0.0280183 , 0.77457757, 0.69413066]])

In [26]:
r = np.random.randint(5,size = 10)
r

array([1, 3, 0, 2, 4, 4, 1, 4, 1, 4])

#  Slicing and Indexing Of arrays

In [27]:
a = np.array([[1,2,3],[4,5,6]])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a[0,0]

1

In [30]:
a[1,2]

6

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [33]:
a[0,1:]

array([2, 3])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# 1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [36]:
#3 and 4
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays

In [37]:
a = np.random.rand(5,2)

In [38]:
a

array([[0.37972635, 0.54903276],
       [0.85936408, 0.74463374],
       [0.90618705, 0.46959899],
       [0.87195979, 0.07425249],
       [0.11332529, 0.0909899 ]])

In [39]:
a.reshape(2,5)

array([[0.37972635, 0.54903276, 0.85936408, 0.74463374, 0.90618705],
       [0.46959899, 0.87195979, 0.07425249, 0.11332529, 0.0909899 ]])

In [40]:
a.reshape(10,1)

array([[0.37972635],
       [0.54903276],
       [0.85936408],
       [0.74463374],
       [0.90618705],
       [0.46959899],
       [0.87195979],
       [0.07425249],
       [0.11332529],
       [0.0909899 ]])

In [41]:
a.reshape(1,10)

array([[0.37972635, 0.54903276, 0.85936408, 0.74463374, 0.90618705,
        0.46959899, 0.87195979, 0.07425249, 0.11332529, 0.0909899 ]])

In [42]:
a.reshape(5,-1)

array([[0.37972635, 0.54903276],
       [0.85936408, 0.74463374],
       [0.90618705, 0.46959899],
       [0.87195979, 0.07425249],
       [0.11332529, 0.0909899 ]])

# Aggregate Functions

* A python numpy aggregate functions are sum, min,max,mean,avg,product,median,standard deviation

In [44]:
a.min()

0.07425248573962284

In [45]:
a.std()

0.31746543268961486

In [46]:
a.var()

0.1007843009528044

# Stacking

In [47]:
a = np.array ([1,2,3,4,5])
b = np.array ([6,7,8,9,10])

In [48]:
np.hstack([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.vstack([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])